apiVersion: v1
kind: Pod
metadata:
  name: sleep-forever
spec:
  containers:
  - name: sleep
    image: ncking/p-bige:latest
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 3600; done"]
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        nvidia.com/gpu: 1
    volumeMounts:
    - name: biomechanics-dataset
      mountPath: /home/mnt/data
  volumes:
  - name: biomechanics-dataset
    persistentVolumeClaim:
      claimName: add-biomechanics-dataset-pvc
  restartPolicy: Never